# Generated by Django 2.2.16 on 2020-10-21 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxa_juros', models.FloatField()),
                ('endereco_ip', models.GenericIPAddressField()),
                ('data_solicitacao', models.DateField()),
                ('banco', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=7)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.Emprestimo')),
            ],
        ),
    ]
